name: CINAME
on: [push] 
jobs:
  run-git-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Js Actions
        id: greet
        uses: actions/hi-world-javascript-action@main
        with:
          who-to-greet: pruthviraj rajput 
      - name: Log Gretting Time
        run: echo "${{ steps.greet.outputs.time }}"