name: CINAME
on: [push] 
jobs:
  run-git-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List of files
        run: |
          pwd
          ls -a
      - name: checkout
        
        uses: actions/checkout@main
        
        with:
          who-to-greet: pruthviraj rajput 
      - name: Log Gretting Time
        run: echo "${{ steps.outputs.time }}"