name: CINAME
on: [push] 
jobs:
  run-git-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List of files
        run: |
          pwd
          ls -a
      - name: checkout
        id: greet
        uses: actions/checkout@main
      - name: List of files after checkout
        run: |
          pwd
          ls -a
        with:
          who-to-greet: pruthviraj rajput 
      - name: Log Gretting Time
        run: echo "${{ steps.greet.outputs.time }}"