
---
name: CINAME
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master
jobs:
  run-git-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List of files
        run: |
          pwd
          ls -a
      - name: checkoutNEw
        
        uses: actions/checkout@main
        
        
      - name: Log Gretting Time
        run: echo "${{ steps.outputs.time }}"
...
---
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "{pruthvirajsing}"
     
...