
---
name: CINAME
on:
  schedule:
    - cron: "*/2 * * * *"
    - cron: "*/1 * * * *"
  push:
    
    
    
jobs:
  run-git-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List of files
        run: |
          pwd
          ls -a
      - name: checkoutNEw
        
        uses: actions/checkout@main
        
        
      - name: Log Gretting Time
        run: echo "${{ steps.outputs.time }}"
...
# ---
# name: CicdSetUp
# on: [push]
# jobs:
#   run-git-actions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Fetch all history for all tags and branches
#       - uses: actions/checkout@v3
#         with:
#          fetch-depth: 0
