name: CicdSetUp
on: [push]
jobs:
  run-git-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all history for all tags and branches
      - uses: newFiles/checkout@v3
        with:
         fetch-depth: 0

